"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""


def find_fib(max):
    p1 = 0
    p2 = 1
    next_ = 0
    result = 0
    while next_ < max:
        if next_ % 2 == 0:
            result += next_

        next_ = p2 + p1
        p1 = p2
        p2 = next_

    return result


assert find_fib(90) == sum([2,  8, 34])
assert find_fib(10) == 2 + 8
assert find_fib(20) == 2 + 8
assert find_fib(50) == 2 + 8 + 34

print('Result =>', find_fib(4_000_000))
